name: flutter_linkify_fork
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 1.1.0
homepage: https://github.com/JahidHasanCO/flutter_linkify_fork

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  linkify: ^5.0.0

dev_dependencies:
  test: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
